export const styles: Record<string, React.CSSProperties> = {
    container: {
        position: "relative",
        zIndex: 10,
        padding: "2rem",
        maxWidth: "800px",
        margin: "0 auto",
        backgroundColor: "#ffffff",
        borderRadius: "12px",
        boxShadow: "0 4px 8px rgba(0, 0, 0, 0.1)",
        textAlign: "center" as "center",
    },
    header: {
        position: "relative",
        backgroundColor: "#1E3A8A",
        color: "white",
        padding: "4rem 0",
        display: "flex",
        flexDirection: "column" as "column",
        alignItems: "center",
        justifyContent: "center",
        textAlign: "center",
    },
    content: {
        padding: "2rem",
        color: "#333",
    },
    logo: {
        width: "15rem",
        height: "auto",
    },
    input: {
        width: "100%",
        padding: "10px",
        fontSize: "1.2rem",
        marginBottom: "1rem",
        border: "1px solid #ccc",
        borderRadius: "6px",
    },
    textarea: {
        width: "100%",
        padding: "10px",
        fontSize: "1.2rem",
        border: "1px solid #ccc",
        borderRadius: "6px",
        resize: "none",
    },
    buttonContainer: {
        display: "flex",
        justifyContent: "center",
        gap: "1rem",
        marginTop: "2rem",
    },
    button: {
        padding: "10px 20px",
        fontSize: "1rem",
        color: "white",
        border: "none",
        borderRadius: "6px",
        cursor: "pointer",
        transition: "background 0.3s",
    },
    editButton: {
        backgroundColor: "#1E3A8A",
    },
    saveButton: {
        backgroundColor: "#15803D",
    },
    deleteButton: {
        backgroundColor: "#B91C1C",
    },
    backButton: {
        backgroundColor: "#555",
    },
    membrosList: {
        marginTop: "2rem",
        textAlign: "left",
    },
    membroItem: {
        display: "flex",
        justifyContent: "space-between",
        padding: "1rem",
        borderRadius: "8px",
        backgroundColor: "#f9fafb",
        boxShadow: "0 2px 5px rgba(0, 0, 0, 0.1)",
        marginBottom: "1rem",
    },
    membroInfo: {
        display: "flex",
        flexDirection: "column",
        alignItems: "flex-start",
        gap: "5px",
    },
    membroNome: {
        fontWeight: "bold",
        fontSize: "1.1rem",
    },
    membroCargo: {
        fontSize: "1rem",
        color: "#555",
    },
    membroCurso: {
        fontSize: "0.9rem",
        color: "#777",
    },
    membroActions: {
        display: "flex",
        alignItems: "center",
        gap: "1rem",
    },
    membroActionButton: {
        padding: "6px 12px",
        fontSize: "0.9rem",
        color: "white",
        backgroundColor: "#4B8DFF",
        border: "none",
        borderRadius: "6px",
        cursor: "pointer",
        transition: "background 0.3s",
    },
    membroActionButtonHover: {
        backgroundColor: "#3b79e0",
    },
};